services:
  - type: web
    name: mhebazar-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mhebazar-db
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
databases:
  - name: mhebazar-db
    plan: free
